<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class' => '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class',
    'Action' => 'Acción',
    'Are you sure to delete this item?' => '¿Está seguro de eliminar este elemento?',
    'Assign' => 'Asignar',
    'Assignment : {0}' => 'Tarea : {0}',
    'Assignments' => 'Tareas',
    'Class Name' => 'Nombre de la clase',
    'Create' => 'Crear',
    'Create Rule' => 'Crear regla',
    'Create Role' => 'Crear Rol',
    'Data' => 'Datos',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Invalid rule "{value}"' => 'Regla no válida "{value}"',
    'Item has been removed.' => 'El artículo ha sido eliminado.',
    'Item has been saved.' => 'El artículo ha sido guardado.',
    'Name' => 'Nombre',
    'Permissions' => 'Permisos',
    'Refresh' => 'Actualizar',
    'Remove' => 'Remover',
    'Roles' => 'Roles',
    'Role : {0}' => 'Rol : {0}',
    'Permission : {0}' => 'Permisos : {0}',
    'Create Permission' => 'Crear Permisos',
    'Routes' => 'Rutas',
    'Rule' => 'Regla',
    'Rule "{value}" does not exists' => 'La regla "{value}" no existe',
    'Rule : {0}' => 'Regla: {0}',
    'Rule Name' => 'Nombre de la regla',
    'Rule has been deleted.' => 'La regla ha sido eliminada.',
    'Rule has been saved.' => 'La regla ha sido guardada.',
    'Rules' => 'Reglas',
    'Search for assigned' => 'Buscar asignado',
    'Search for available' => 'Buscar disponibles',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'Type' => 'Tipo',
    'Unknown class \'{class}\'' => 'Clase desconocida \'{class}\'',
    'Update' => 'Actualizar',
    'Update Rule : {0}' => 'Actualizar Regla : {0}',
    'Update Role : {0}' => 'Actualizar funcion : {0}',
    'Update Permission : {0}' => 'Permiso de actualización: {0}',
    'Select Rule' => 'Seleccionar regla',
];
